### ISSUE TITLE
Websocket Integration Guide

### ISSUE THREAD

**Issue by Fedack** [MausTec/nogasm-wifi#1]
Greetings,
I'd like to be able to connect to the websocket, could you make a guide on what different commands and what is to be expected so that I could make my own remote interface?

Thanks

**Comment by MauAbata** [comment]
Websocket documentation has been added at https://github.com/MausTec/nogasm-wifi/blob/master/doc/WebSocket.md

**Comment by Fedack** [comment]
Oh great, thanks!
